// Sample doctor data for seeding
const sampleDoctors = [
    {
        name: 'Dr. Rajesh Sharma',
        specialization: 'Cardiology',
        qualification: 'MBBS, MD',
        experience: 15,
        consultation_fee: 1500,
        rating: 4.8,
        total_reviews: 245,
        hospital_name: 'Apollo Hospitals',
        hospital_address: '123, MG Road, Mumbai, Maharashtra',
        city: 'Mumbai',
        state: 'Maharashtra',
        available_days: 'Monday, Tuesday, Wednesday, Thursday, Friday',
        available_time_slots: '09:00-17:00',
        profile_image: 'https://randomuser.me/api/portraits/men/1.jpg',
        is_active: 1
    },
    {
        name: 'Dr. Priya Patel',
        specialization: 'Dermatology',
        qualification: 'MBBS, MD',
        experience: 10,
        consultation_fee: 800,
        rating: 4.6,
        total_reviews: 180,
        hospital_name: 'Fortis Healthcare',
        hospital_address: '456, Park Street, Delhi, Delhi',
        city: 'Delhi',
        state: 'Delhi',
        available_days: 'Monday, Wednesday, Friday, Saturday',
        available_time_slots: '10:00-18:00',
        profile_image: 'https://randomuser.me/api/portraits/women/2.jpg',
        is_active: 1
    },
    {
        name: 'Dr. Amit Kumar',
        specialization: 'Pediatrics',
        qualification: 'MBBS, MD',
        experience: 12,
        consultation_fee: 700,
        rating: 4.7,
        total_reviews: 320,
        hospital_name: 'Max Healthcare',
        hospital_address: '789, Commercial Street, Bangalore, Karnataka',
        city: 'Bangalore',
        state: 'Karnataka',
        available_days: 'Tuesday, Wednesday, Thursday, Friday, Saturday',
        available_time_slots: '09:00-17:00',
        profile_image: 'https://randomuser.me/api/portraits/men/3.jpg',
        is_active: 1
    },
    {
        name: 'Dr. Sunita Verma',
        specialization: 'Gynecology',
        qualification: 'MBBS, MS',
        experience: 18,
        consultation_fee: 1200,
        rating: 4.9,
        total_reviews: 410,
        hospital_name: 'Manipal Hospitals',
        hospital_address: '321, Hill Road, Hyderabad, Telangana',
        city: 'Hyderabad',
        state: 'Telangana',
        available_days: 'Monday, Tuesday, Wednesday, Thursday, Friday, Saturday',
        available_time_slots: '10:00-18:00',
        profile_image: 'https://randomuser.me/api/portraits/women/4.jpg',
        is_active: 1
    },
    {
        name: 'Dr. Vikram Singh',
        specialization: 'Orthopedics',
        qualification: 'MBBS, MS',
        experience: 20,
        consultation_fee: 1300,
        rating: 4.8,
        total_reviews: 380,
        hospital_name: 'KIMS Hospitals',
        hospital_address: '654, Marine Drive, Chennai, Tamil Nadu',
        city: 'Chennai',
        state: 'Tamil Nadu',
        available_days: 'Monday, Tuesday, Wednesday, Thursday, Friday',
        available_time_slots: '08:00-16:00',
        profile_image: 'https://randomuser.me/api/portraits/men/5.jpg',
        is_active: 1
    },
    {
        name: 'Dr. Neha Gupta',
        specialization: 'General Medicine',
        qualification: 'MBBS, MD',
        experience: 8,
        consultation_fee: 500,
        rating: 4.5,
        total_reviews: 150,
        hospital_name: 'Narayana Health',
        hospital_address: '987, Brigade Road, Pune, Maharashtra',
        city: 'Pune',
        state: 'Maharashtra',
        available_days: 'Monday, Wednesday, Friday',
        available_time_slots: '09:00-13:00, 16:00-20:00',
        profile_image: 'https://randomuser.me/api/portraits/women/6.jpg',
        is_active: 1
    },
    {
        name: 'Dr. Sanjay Malhotra',
        specialization: 'Neurology',
        qualification: 'MBBS, DM',
        experience: 22,
        consultation_fee: 1800,
        rating: 4.9,
        total_reviews: 520,
        hospital_name: 'Medanta',
        hospital_address: '147, Linking Road, Ahmedabad, Gujarat',
        city: 'Ahmedabad',
        state: 'Gujarat',
        available_days: 'Tuesday, Thursday, Saturday',
        available_time_slots: '11:00-19:00',
        profile_image: 'https://randomuser.me/api/portraits/men/7.jpg',
        is_active: 1
    },
    {
        name: 'Dr. Anjali Reddy',
        specialization: 'Ophthalmology',
        qualification: 'MBBS, MS',
        experience: 14,
        consultation_fee: 900,
        rating: 4.7,
        total_reviews: 290,
        hospital_name: 'Artemis Hospital',
        hospital_address: '258, Juhu Beach Road, Kolkata, West Bengal',
        city: 'Kolkata',
        state: 'West Bengal',
        available_days: 'Monday, Tuesday, Wednesday, Thursday, Friday, Saturday',
        available_time_slots: '10:00-18:00',
        profile_image: 'https://randomuser.me/api/portraits/women/8.jpg',
        is_active: 1
    },
    {
        name: 'Dr. Rohan Kapoor',
        specialization: 'ENT',
        qualification: 'MBBS, MS',
        experience: 11,
        consultation_fee: 750,
        rating: 4.6,
        total_reviews: 210,
        hospital_name: 'BLK Super Speciality Hospital',
        hospital_address: '369, Carter Road, Jaipur, Rajasthan',
        city: 'Jaipur',
        state: 'Rajasthan',
        available_days: 'Monday, Wednesday, Friday, Saturday',
        available_time_slots: '09:00-17:00',
        profile_image: 'https://randomuser.me/api/portraits/men/9.jpg',
        is_active: 1
    },
    {
        name: 'Dr. Kavya Iyer',
        specialization: 'Psychiatry',
        qualification: 'MBBS, MD',
        experience: 9,
        consultation_fee: 1000,
        rating: 4.8,
        total_reviews: 175,
        hospital_name: 'Saket City Hospital',
        hospital_address: '741, Connaught Place, Lucknow, Uttar Pradesh',
        city: 'Lucknow',
        state: 'Uttar Pradesh',
        available_days: 'Tuesday, Wednesday, Thursday, Friday',
        available_time_slots: '10:00-14:00, 17:00-21:00',
        profile_image: 'https://randomuser.me/api/portraits/women/10.jpg',
        is_active: 1
    }
];

module.exports = sampleDoctors;
